travis:
  secure:
    BINSTAR_TOKEN: nxom6JY/0piCOpQWtaaiCVn4BmugPeOOjTytWJ32ITdrAj8AU4oCM5uNV6K9oR7g1vt+iVX/TddnlxgSP7321a1813yDriN7586gu527hlF3X+luIHvzDpQmjkOqD13+tpEi+aOT+W5VsFC+dpxfVvPaq1dtryh5NjP1QzMbMEdoVzLTkX7Ttb92zmgusrQDMAZISSjOuXLYxRE/Kt016iOpWb/b3sJZqZpVvZyIu8YhT7kZp7lDoEOxlrQvIcbMKhbv4hg4Jwn/afR2LaCqVxJpkLzjgfbdz5lpnHC1legxa6nJLAO6+r10F18b/yHXNUXMmJu0kbB+OViLEzkcAcaWhdSghwW/frktrE2t6DEftWDKCsxHTVwAS7wp9Ites+KnvQIP3L3VtYppKsTI3mbag7zbfc294QPTnnxB5yytxHL+dpu2KY8XoHTFT5eYkbHIduQ4sn4nWB7aZaAfc5bWjtXBGl7U26eujCmxZYaUXDxnkgVM23WexIWbbSlOb+wUrU/ioPVuhyAzxwGAi73kocYxIajAXqi8Jxqwxfw2SCn9EUUAU9YI0BY2YgG2DFUGm4cEnHRwf8Y/Cb56TdLqbQaiS8yRoy5lE6KEqjU99PaNbUGYlR8SQ4X6plaWHsma++4bsn7mSNoTJZaNq79bRSo/HkwZ63e6v63zlaI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
