travis:
  secure:
    BINSTAR_TOKEN: M2lpg5lupJPOntkqh9SYnhJqNOQIiV05n8lnhzT22GZf0QZdeURxtOcuiAU431RNNQazR3SJhvwt8CReR2aTeODESU4gnhoFRSfOsyaYBBYGTZ98ez6N6HJuzGIms3G/jDoISsMGsGB9uxQTTwonKvKEJ2pS9GmSIMH+6xzu3dO6Y6l6P9YXdbXjQCuVtBujLbkE2dEUxWi24ydbegYGx6esHxwwujOE3uvpOMtrUWD/mXQxhk3WscBlrWIJiSwUlLoulTIFpqdPm/vtyrcaqNGogB1g4s9HC34ygDwT4xg6pR9WeL5691dvfbXTCxlA7Z8Uk6z8laBGfpNAJNmJl4cclKZPw87k5gAnzn1g20ZkLpf4bD7CD4SIo9/BwItykj90Lbr3xltBUl75P+UFSCEC//1DhGmNqWnFoinDIdHOfL/HS/oTkeTj/yIjrJD77lhEjvdCunUdxmauNXBW5zgc70XUeYIf9KSe1TEGsJ9qLORY5N2nH0gh1T340++wxBLKJrF6Gpk9jdyMx+pd1IoVnx7nQHS7//uBjPdMq2rfkwAg/PctKkLuhaPugtXGhd8p3yDaLIIQGSyWeYaXYUalNIO6eJ71sNttMQ5hX6BwWJEpOQWz/tLCXZO//P6k1iVHJ5+Wq7lRMc364yj6NGErE3UySKkrMKZnov3RAT8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
